### ISSUE TITLE
compile and declare version conflicts

### ISSUE THREAD

**Issue by tgyf007** [reddio-com/cairo#1]
I found that it can only be compiled with starknet-compile 1.0.*, but an error is reported when declare:

Got BadRequest while trying to access https://alpha4.starknet.io/gateway/add_transaction. Status code: 400; text: {"code": "StarknetErrorCode.INVALID_CONTRACT_CLASS", "message": "Compiled versions older than 1.1.0 are not supported. Got an old version."}.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/services/external_api/client.py", line 187, in _send_request
    return await self._parse_response(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/services/external_api/client.py", line 231, in _parse_response
    raise BadRequest(status_code=response.status, text=text)
services.external_api.client.BadRequest: HTTP error ocurred. Status: 400. Text: {"code": "StarknetErrorCode.INVALID_CONTRACT_CLASS", "message": "Compiled versions older than 1.1.0 are not supported. Got an old version."}
Error: BadRequest: HTTP error ocurred. Status: 400. Text: {"code": "StarknetErrorCode.INVALID_CONTRACT_CLASS", "message": "Compiled versions older than 1.1.0 are not supported. Got an old version."}

**Comment by Cevedale** [comment]
The error message indicates that the contract you are trying to interact with has been compiled with a version older than 1.1.0, and this older version is not supported on the server you are trying to access.

You should update your Starknet contract, you may need to recompile your contract with an updated Starknet compiler if necessary.
Make sure that the server you are connecting to supports the Starknet contract version you are using. It's possible that the server you are using is not updated to support older contract versions.
Verify that you are using the correct versions and that there are no issues with your contract code. Also take a look at the Starknet documentation or the server provider's documentation to see if there are any specific requirements or updates you need to make.
